# Site settings
title: Club de Algoritmos de Sinaloa
email: admin@algoritmos.club
description: >-
  Club dedicado al estudio de algoritmos y entrenamiento en programación competitiva, enfocado en escuelas de nivel
  universitario del estado de Sinaloa, México.
baseurl: ""
url: "http://algoritmos.club"
locale: "es"
date_format: "%Y-%m-%d"
timezone: America/Mazatlan
minimal_mistakes_skin: "dark"

github_username:  club-de-algoritmos

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Feature settings
search: true
lunr:
  search_within_pages: true

include:
  - _pages
  - _posts
  - _redirects

exclude:
  - CNAME
  - Gemfile*
  - LICENSE
  - README.md

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename
      title: " "
      layout: single
      sidebar:
        - image: /assets/images/logo.png
          image_alt: "Logo"
          nav: pages
  # _redirects
  - scope:
      path: "_redirects"
      type: pages
    values:
      permalink: /:basename
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: /:year/:month/:day/:title
      layout: single
      read_time: true

atom_feed:
  hide: true

analytics:
  provider: "google-gtag"
  google:
    anonymize_ip: false
    tracking_id: "G-ENM5RCJ7PS"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/club-de-algoritmos"
